Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2018-11, with the labels that each got.

#2024 Reduce number of test targets
  test/CMakeLists.txt
  test/opt/CMakeLists.txt
  test/opt/aggressive_dead_code_elim_test.cpp
  test/stats/CMakeLists.txt
  test/tools/opt/CMakeLists.txt
  test/util/CMakeLists.txt
Labels: dev:building

#2044 Validate variable types for UniformConstant storage in Vulkan (#2008)
  source/val/validate_memory.cpp
  test/val/CMakeLists.txt
  test/val/val_builtins_test.cpp
  test/val/val_decoration_test.cpp
  test/val/val_memory_test.cpp
Labels: component:validation

#2052 Ensure for OpVariable that result type and storage class operand agree
  source/val/validate_memory.cpp
  test/opt/ir_builder.cpp
  test/val/val_id_test.cpp
  test/val/val_memory_test.cpp
  test/val/val_ssa_test.cpp
  test/val/val_storage_test.cpp
Labels: kokoro:run

#2077 Validate component literals for OpVectorShuffle in WebGPU environment
  source/spirv_target_env.cpp
  source/spirv_target_env.h
  source/val/validate_composites.cpp
  test/val/val_id_test.cpp
Labels: api:webgpu

#2082 Add tests for matrix type data rule validation
  test/val/val_id_test.cpp
Labels: api:webgpu, component:validation

#2083 Add missing override to ProcessLinesPass
  source/opt/process_lines_pass.h
Labels: component:optimization, dev:building

#2085 Update build instructions: add effcee, re2
  README.md
Labels: dev:building

#2089 Validate that debugging instructions are not present for WebGPU
  source/opcode.cpp
  source/opcode.h
  source/val/validate_debug.cpp
  test/val/val_webgpu_test.cpp
Labels: api:webgpu, component:validation

#2090 Check forbidden Annotation instructions for WebGPU env
  source/val/validate_annotation.cpp
  test/val/val_decoration_test.cpp
Labels: api:webgpu, component:validation

#2087 Add tests coverage for OpTypeVector column count validation
  test/val/val_id_test.cpp
Labels: api:webgpu, component:validation

#2093 Ensure correct Addressing and Memory model set for WebGPU
  source/val/validate_instruction.cpp
  test/val/val_decoration_test.cpp
  test/val/val_id_test.cpp
  test/val/val_version_test.cpp
  test/val/val_webgpu_test.cpp
Labels: api:webgpu, component:validation

#2092 Make sure that initialized variable have correct storage class
  source/val/validate_memory.cpp
  test/val/val_memory_test.cpp
Labels: api:webgpu, component:validation

#2098 Add newline at end of file
  source/reduce/reducer.cpp
Labels: bug

#2099 New spirv-reduce reduction pass: operand to dominating id.
  source/operand.cpp
  source/operand.h
  source/opt/instruction.h
  source/reduce/CMakeLists.txt
  source/reduce/change_operand_reduction_opportunity.h
  source/reduce/operand_to_const_reduction_pass.cpp
  source/reduce/operand_to_dominating_id_reduction_pass.cpp
  source/reduce/operand_to_dominating_id_reduction_pass.h
  test/reduce/CMakeLists.txt
  test/reduce/operand_to_dominating_id_reduction_pass_test.cpp
  tools/reduce/reduce.cpp
Labels: component:reducer

#2113 Restrict capabilities to WebGPU spec
  source/val/validate_capability.cpp
  test/val/val_capability_test.cpp
  test/val/val_decoration_test.cpp
  test/val/val_webgpu_test.cpp
Labels: api:webgpu, component:validation

#2118 Ensure that function parameter's type is not void
  source/val/validate_type.cpp
  test/val/val_id_test.cpp
Labels: api:opencl, api:vulkan, api:webgpu, component:validation

#2119 Ensure that imported extended instructions for WebGPU are only "GLSL.std.450"
  Android.mk
  source/CMakeLists.txt
  source/val/validate.cpp
  source/val/validate.h
  source/val/validate_extensions.cpp
  test/val/val_webgpu_test.cpp
Labels: api:webgpu, component:validation

#2124 Move OpExtInst validation into validate_extensions.cpp
  Android.mk
  source/CMakeLists.txt
  source/val/validate.cpp
  source/val/validate.h
  source/val/validate_ext_inst.cpp
  source/val/validate_extensions.cpp
Labels: component:validation

#2126 [ndk-build] Make SPIRV-Headers location configurable
  Android.mk
Labels: dev:building

#2129 Fixup BUILD.gn file
  BUILD.gn
Labels: dev:building

#2127 Ensure that only whitelisted extensions are used in WebGPU
  source/val/validate_extensions.cpp
  test/val/val_webgpu_test.cpp
Labels: api:webgpu, component:validation

#2131 Merge two implementations of ValidateExecutionScope
  Android.mk
  BUILD.gn
  source/CMakeLists.txt
  source/val/validate_barriers.cpp
  source/val/validate_non_uniform.cpp
  source/val/validate_scopes.cpp
  source/val/validate_scopes.h
Labels: api:vulkan, component:validation

#2132 Merging two ValidateMemoryScope implementations
  source/val/validate_atomics.cpp
  source/val/validate_barriers.cpp
  source/val/validate_scopes.cpp
  source/val/validate_scopes.h
  test/val/val_atomics_test.cpp
Labels: api:vulkan, component:validation

#2144 Add check for QueueFamilyKHMR memory scope
  source/val/validate_scopes.cpp
  test/val/val_atomics_test.cpp
Labels: api:vulkan, api:webgpu, component:validation
