Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2018-09, with the labels that each got.

#1875 BUILD.gn: Make a better interface with dependents.
  BUILD.gn
Labels: dev:building

#1884 Roll spirv-headers in DEPS
  DEPS
Labels: dev:building

#1886 Fixup BUILD.gn file
  BUILD.gn
Labels: dev:building

#1924 Remove stats use of internal API
  test/stats/stats_aggregate_test.cpp
  tools/stats/spirv_stats.cpp
  tools/stats/spirv_stats.h
  tools/stats/stats.cpp
Labels: component:compression, dev:refactoring

#1926 Remove SetContextMessageConsumer from markv_codec_test
  test/comp/markv_codec_test.cpp
Labels: dev:refactoring

#1925 Remove use of SetContextMessageConsumer from binary_parse_test
  test/binary_parse_test.cpp
Labels: dev:refactoring

#1934 Unify memory instruction validation style
  source/val/validate.cpp
  source/val/validate.h
  source/val/validate_memory.cpp
Labels: dev:refactoring
