Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2018-12, with the labels that each got.

#2152 Fixup BUILD.gn from addtion of upgrade_memory_model
  BUILD.gn
Labels: bug, dev:building

#2148 Add WebGPU Execution scope check
  source/val/validate_scopes.cpp
  test/val/val_barriers_test.cpp
Labels: api:webgpu, component:validation

#2146 Validate uses of ids defined in unreachable blocks.
  source/val/validate_id.cpp
  test/val/val_id_test.cpp
Labels: fuzzer

#2158 [val] Fixup id name output
  source/val/validate.cpp
  source/val/validation_state.cpp
  source/val/validation_state.h
  test/cpp_interface_test.cpp
  test/val/val_adjacency_test.cpp
  test/val/val_arithmetics_test.cpp
  test/val/val_atomics_test.cpp
  test/val/val_barriers_test.cpp
  test/val/val_cfg_test.cpp
  test/val/val_composites_test.cpp
  test/val/val_conversion_test.cpp
  test/val/val_data_test.cpp
  test/val/val_decoration_test.cpp
  test/val/val_derivatives_test.cpp
  test/val/val_ext_inst_test.cpp
  test/val/val_id_test.cpp
  test/val/val_image_test.cpp
  test/val/val_limits_test.cpp
  test/val/val_memory_test.cpp
  test/val/val_ssa_test.cpp
Labels: component:validation

#2157 Remove undefined behaviour when folding shifts.
  source/opt/fold.cpp
  test/opt/fold_test.cpp
Labels: fuzzer

#2156 Validate OpForwardPointer
  source/val/validate_type.cpp
  test/val/val_data_test.cpp
  test/val/val_id_test.cpp
Labels: fuzzer

#2169 Check that if A calls B, B is defined before A for WebGPU
  source/val/validate.cpp
  source/val/validation_state.h
  test/val/val_layout_test.cpp
Labels: api:webgpu, component:validation

#2161 Check for recursion in Vulkan and WebGPU entry points
  source/val/validate.cpp
  source/val/validation_state.cpp
  source/val/validation_state.h
  test/val/val_validation_state_test.cpp
Labels: api:vulkan, api:webgpu, component:validation

#2174 Fix broken recurison validation tests
  test/val/val_validation_state_test.cpp
Labels: api:webgpu, component:validation

#2175 Merge two implementations of ValidateMemorySemantics
  Android.mk
  BUILD.gn
  source/CMakeLists.txt
  source/val/validate_atomics.cpp
  source/val/validate_barriers.cpp
  source/val/validate_memory_semantics.cpp
  source/val/validate_memory_semantics.h
  test/val/val_atomics_test.cpp
  test/val/val_barriers_test.cpp
Labels: component:validation

#2180 Restrict mask bits for memory semantics in WebGPU
  source/val/validate_memory_semantics.cpp
  test/val/val_atomics_test.cpp
Labels: api:webgpu, component:validation

#2172 Fix invalid OpPhi generated by merge-return.
  source/opt/merge_return_pass.cpp
  test/opt/pass_merge_return_test.cpp
Labels: bug, component:optimization

#2193 Disable checking that AtomicStorage capability is present
  source/val/validate_memory_semantics.cpp
  test/val/val_atomics_test.cpp
Labels: api:vulkan, component:validation

#2243 Remove check for SpvCapabilityAtomicStorage
  source/val/validate_memory_semantics.cpp
  test/val/val_atomics_test.cpp
Labels: api:vulkan, component:validation

#2217 Implement initial --webgpu-mode flag
  include/spirv-tools/optimizer.hpp
  source/opt/optimizer.cpp
  tools/opt/opt.cpp
Labels: api:webgpu
