Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2018-08, with the labels that each got.

#1758 Update diag() use in validate_builtin.
  source/val/validate_builtins.cpp
Labels: dev:refactoring

#1760 Update diag() calls in validate_cfg.
  source/val/validate_cfg.cpp
  test/val/val_cfg_test.cpp
Labels: dev:refactoring

#1762 Update diag() calls in validate_conversion.
  source/val/validate_conversion.cpp
Labels: dev:refactoring

#1763 Update diag() calls in validate_datarules.
  source/val/validate_datarules.cpp
Labels: dev:refactoring

#1755 Remove std::deque in favour of std::vector.
  source/comp/markv_codec.cpp
  source/operand.h
  source/spirv_stats.cpp
  source/val/validate.cpp
  source/val/validation_state.cpp
  source/val/validation_state.h
Labels: dev:refactoring

#1764 Update diag() calls in validate_decorations.
  source/val/validate_decorations.cpp
Labels: dev:refactoring

#1765 Update diag() calls in validate_derivatives.
  source/val/validate_derivatives.cpp
Labels: dev:refactoring

#1766 Update diag() calls in validate_ext_inst.
  source/val/validate_ext_inst.cpp
Labels: dev:refactoring

#1767 Update diag() calls in validate_image.
  source/val/validate_image.cpp
Labels: dev:refactoring

#1768 Update diag() calls in validate_instruction.
  source/val/validate_instruction.cpp
Labels: dev:refactoring

#1769 Update diag() call in validate_interface.
  source/val/validate_interfaces.cpp
Labels: dev:refactoring

#1770 Update diag() calls in validate_layout.
  source/val/validate_layout.cpp
Labels: dev:refactoring

#1771 Update diag() calls in validate_literals.
  source/val/validate_literals.cpp
Labels: dev:refactoring

#1772 Update diag() calls in validate_logicals.
  source/val/validate_logicals.cpp
Labels: dev:refactoring

#1773 Update diag() calls in validate_non_uniform.
  source/val/validate_non_uniform.cpp
Labels: dev:refactoring

#1774 Update diag() calls in validate_primitives.
  source/val/validate_primitives.cpp
Labels: dev:refactoring

#1775 Update diag() calls in validate_type_unique.
  source/val/validate_type_unique.cpp
Labels: dev:refactoring

#1759 Update diag() calls in validate_capability.
  source/val/validate_capability.cpp
Labels: dev:refactoring

#1779 Fixup BUILD.gn to use a group for SPIRV-Tools
  BUILD.gn
Labels: dev:building

#1776 Remove diag() overloads.
  source/val/validate_id.cpp
  source/val/validation_state.cpp
  source/val/validation_state.h
  test/val/val_ssa_test.cpp
Labels: dev:refactoring

#1756 Remove using std::<foo> statements.
  source/cfa.h
  source/opt/cfg.cpp
  source/opt/local_single_store_elim_pass.cpp
  source/opt/mem_pass.cpp
  source/val/basic_block.cpp
  source/val/function.cpp
  source/val/instruction.cpp
  source/val/validate.cpp
  source/val/validate_cfg.cpp
  source/val/validate_decorations.cpp
  source/val/validate_id.cpp
  source/val/validation_state.cpp
  test/binary_to_text_test.cpp
  test/operand_capabilities_test.cpp
  test/operand_test.cpp
  test/text_to_binary.annotation_test.cpp
  test/text_to_binary.control_flow_test.cpp
  test/text_to_binary.mode_setting_test.cpp
  test/text_to_binary.subgroup_dispatch_test.cpp
  test/val/val_arithmetics_test.cpp
  test/val/val_capability_test.cpp
  test/val/val_cfg_test.cpp
  test/val/val_data_test.cpp
  test/val/val_decoration_test.cpp
  test/val/val_extensions_test.cpp
  test/val/val_id_test.cpp
  test/val/val_layout_test.cpp
  test/val/val_limits_test.cpp
  test/val/val_ssa_test.cpp
  test/val/val_state_test.cpp
  test/val/val_type_unique_test.cpp
  test/val/val_validation_state_test.cpp
  test/val/val_version_test.cpp
  test/val/val_webgpu_test.cpp
Labels: dev:refactoring

#1781 Remove instruction_counter from ValidationState.
  source/val/instruction.cpp
  source/val/instruction.h
  source/val/validate.cpp
  source/val/validate_id.cpp
  source/val/validation_state.cpp
  source/val/validation_state.h
Labels: dev:refactoring

#1782 Combine ordered_instruction loops in validation.
  source/val/validate.cpp
  source/val/validate.h
  source/val/validate_adjacency.cpp
  source/val/validate_id.cpp
  source/val/validate_memory.cpp
Labels: dev:refactoring

#1784 Remove ValidateInstructionAndUpdateValidationState
  source/spirv_stats.cpp
  source/val/validate.cpp
  source/val/validate.h
  source/val/validation_state.h
Labels: dev:refactoring

#1786 Simplify validation ProcessInstruction
  source/val/instruction.cpp
  source/val/instruction.h
  source/val/validate.cpp
  source/val/validation_state.cpp
Labels: dev:refactoring

#1790 Validation within function body when doing a FunctionCall.
  source/val/validate.cpp
  test/val/val_layout_test.cpp
Labels: bug

#1806 Simplify MoveToFront
  source/comp/CMakeLists.txt
  source/comp/markv_codec.cpp
  source/util/move_to_front.cpp
  source/util/move_to_front.h
  test/CMakeLists.txt
  test/move_to_front_test.cpp
Labels: dev:refactoring

#1807 Remove unused bit stream methods.
  source/util/bit_stream.cpp
  source/util/bit_stream.h
  test/bit_stream.cpp
Labels: dev:refactoring

#1809 Split MarkV into multiple files
  source/comp/CMakeLists.txt
  source/comp/markv.cpp
  source/comp/markv.h
  source/comp/markv_codec.cpp
  source/comp/markv_codec.h
  source/comp/markv_decoder.cpp
  source/comp/markv_decoder.h
  source/comp/markv_encoder.cpp
  source/comp/markv_encoder.h
  source/comp/markv_logger.h
  source/comp/markv_model.h
Labels: dev:refactoring

#1819 Remove codegen related code.
  tools/comp/markv_model_shader.cpp
  tools/stats/stats.cpp
  tools/stats/stats_analyzer.cpp
  tools/stats/stats_analyzer.h
Labels: dev:refactoring

#1826 Move spirv_stats into tools/stats.
  source/CMakeLists.txt
  test/stats/CMakeLists.txt
  test/stats/stats_aggregate_test.cpp
  test/stats/stats_analyzer_test.cpp
  tools/CMakeLists.txt
  tools/stats/spirv_stats.cpp
  tools/stats/spirv_stats.h
  tools/stats/stats.cpp
  tools/stats/stats_analyzer.cpp
  tools/stats/stats_analyzer.h
Labels: dev:refactoring

#1828 Remove unused stats maps and parameters
  test/stats/stats_aggregate_test.cpp
  tools/stats/spirv_stats.cpp
  tools/stats/spirv_stats.h
Labels: dev:refactoring

#1833 Move bit_stream, move_to_front and huffman_codec.
  Android.mk
  BUILD.gn
  source/CMakeLists.txt
  source/comp/CMakeLists.txt
  source/comp/bit_stream.cpp
  source/comp/bit_stream.h
  source/comp/huffman_codec.h
  source/comp/markv_codec.cpp
  source/comp/markv_codec.h
  source/comp/markv_decoder.h
  source/comp/markv_encoder.h
  source/comp/markv_model.h
  source/comp/move_to_front.cpp
  source/comp/move_to_front.h
  test/CMakeLists.txt
  test/bit_stream.cpp
  test/huffman_codec.cpp
  test/move_to_front_test.cpp
  tools/comp/markv_model_shader.cpp
Labels: dev:refactoring

#1836 Move make_unique to source/util.
  BUILD.gn
  source/CMakeLists.txt
  source/link/linker.cpp
  source/opt/CMakeLists.txt
  source/opt/basic_block.cpp
  source/opt/build_module.cpp
  source/opt/constants.h
  source/opt/dead_branch_elim_pass.cpp
  source/opt/fold_spec_constant_op_and_composite_pass.cpp
  source/opt/loop_descriptor.cpp
  source/opt/merge_return_pass.cpp
  source/opt/optimizer.cpp
  source/opt/scalar_replacement_pass.cpp
  source/opt/set_spec_constant_default_value_pass.cpp
  source/opt/ssa_rewrite_pass.cpp
  source/opt/type_manager.cpp
  source/opt/unify_const_pass.cpp
  source/util/make_unique.h
  source/util/small_vector.h
  test/opt/iterator_test.cpp
  test/opt/pass_fixture.h
  test/opt/pass_manager_test.cpp
  test/opt/types_test.cpp
Labels: dev:refactoring

#1837 Use MakeUnique.
  source/comp/bit_stream.h
  source/comp/markv_codec.cpp
  source/comp/markv_decoder.h
  source/comp/markv_encoder.h
  source/disassemble.cpp
  source/enum_set.h
  source/opt/inline_pass.cpp
  source/opt/ir_context.h
  source/opt/ir_loader.cpp
  source/opt/type_manager.cpp
  source/opt/types.cpp
  source/util/make_unique.h
  source/util/parse_number.cpp
  source/util/small_vector.h
  test/opt/pass_fixture.h
  test/opt/types_test.cpp
  tools/comp/markv_model_factory.cpp
  tools/comp/markv_model_shader.cpp
Labels: dev:refactoring

#1842 Add GN rules to build spriv-as
  BUILD.gn
Labels: dev:building

#1852 [kokoro] Stop building and running tests for VS2013
  kokoro/scripts/windows/build.bat
Labels: dev:ci
