Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2019-10, with the labels that each got.

#2946 Link cfg and dominator analysis in the context
  source/opt/ir_context.cpp
  test/opt/ir_context_test.cpp
Labels: fuzzer-found-issue

#2955 Remove non-existent files from BUILD.gn
  BUILD.gn
Labels: component:reducer

#2956 Use a longer timeout for Bazel tests.
  BUILD.bazel
  build_defs.bzl
Labels: dev:ci

#2931 Keep NOPs when comparing with original binary
  source/opt/optimizer.cpp
  test/opt/optimizer_test.cpp
Labels: fuzzer-found-issue
