Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2019-09, with the labels that each got.

#2834 For WebGPU<->Vulkan optimization, set correct execution environment
  include/spirv-tools/optimizer.hpp
  test/fuzzers/spvtools_opt_vulkantowebgpu_fuzzer.cpp
  test/fuzzers/spvtools_opt_webgputovulkan_fuzzer.cpp
  test/opt/optimizer_test.cpp
  tools/opt/opt.cpp
Labels: api:vulkan, api:webgpu, component:optimization

#2841 Don't register duplicate decoration in validator.
  source/val/validation_state.h
Labels: fuzzer-found-issue

#2844 Handle id overflow in the constant manager.
  source/opt/fold.cpp
  test/opt/constant_manager_test.cpp
Labels: fuzzer-found-issue

#2845 Handle id overflow in the ssa rewriter.
  Android.mk
  BUILD.gn
  source/opt/CMakeLists.txt
  source/opt/cfg.cpp
  source/opt/cfg.h
  source/opt/local_ssa_elim_pass.cpp
  source/opt/local_ssa_elim_pass.h
  source/opt/mem_pass.cpp
  source/opt/mem_pass.h
  source/opt/optimizer.cpp
  source/opt/passes.h
  source/opt/ssa_rewrite_pass.cpp
  source/opt/ssa_rewrite_pass.h
  test/opt/local_ssa_elim_test.cpp
  test/tools/opt/flags.py
Labels: fuzzer-found-issue

#2848 Handle creating a new constant failing gracefully
  source/opt/generate_webgpu_initializers_pass.cpp
Labels: api:vulkan, api:webgpu, component:optimization

#2854 Handle another case where creating a constant can fail
  source/opt/generate_webgpu_initializers_pass.cpp
Labels: api:vulkan, api:webgpu, bug, component:optimization

#2862 Adding OpEntryPoint validation
  source/val/validate.cpp
  source/val/validate.h
  test/val/CMakeLists.txt
  test/val/val_entry_point.cpp
  utils/check_copyright.py
Labels: component:validation

#2876 Add WebGPU SPIR-V Assembler in JavaScript.
  tools/sva/.eslintrc.json
  tools/sva/.gitignore
  tools/sva/README.md
  tools/sva/bin/sva.js
  tools/sva/mocha.opts
  tools/sva/package.json
  tools/sva/rollup.config.js
  tools/sva/src/assembler.js
  tools/sva/src/assembler_test.js
  tools/sva/src/ast.js
  tools/sva/src/lexer.js
  tools/sva/src/lexer_test.js
  tools/sva/src/parser.js
  tools/sva/src/parser_test.js
  tools/sva/src/spirv.data.js
  tools/sva/src/sva.js
  tools/sva/src/token.js
  tools/sva/tests/empty_main.spv_asm
  tools/sva/tests/index.html
  tools/sva/tests/simple.spv_asm
  tools/sva/tools/process_grammar.rb
  tools/sva/yarn.lock
Labels: component:as/dis

#2882 Fix header include syntax.
  source/opt/function.cpp
  source/opt/optimizer.cpp
  tools/util/cli_consumer.h
Labels: dev:building

#2885 Add OpCopyMemory test to SVA.
  tools/sva/src/parser.js
  tools/sva/src/parser_test.js
Labels: dev:testing, enhancement

#2908 Handle id overflow in convert local access chains
  source/opt/local_access_chain_convert_pass.cpp
  source/opt/local_access_chain_convert_pass.h
  test/opt/local_access_chain_convert_test.cpp
Labels: fuzzer-found-issue

#2916 Handle id overflow in wrap-opkill
  source/opt/wrap_opkill.cpp
  test/opt/wrap_opkill_test.cpp
Labels: fuzzer-found-issue

#2923 Add removing references to debug instructions when removing them
  source/opt/ir_context.h
  source/opt/module.h
  source/opt/strip_debug_info_pass.cpp
  test/opt/strip_debug_info_test.cpp
Labels: component:optimization
