Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2019-07, with the labels that each got.

#2725 Update memory scope rules for WebGPU
  source/val/validate_scopes.cpp
  test/val/val_atomics_test.cpp
Labels: api:webgpu, component:validation

#2730 Update execution scope rules for WebGPU
  source/val/validate_scopes.cpp
  test/val/val_barriers_test.cpp
Labels: api:webgpu, component:validation

#2737 Correctly implement WebGPU related flag exclusions
  test/tools/expect.py
  test/tools/opt/flags.py
  tools/opt/opt.cpp
Labels: api:webgpu, bug, component:optimization

#2767 Fix #2609 - Handle out-of-bounds scalar replacements.
  source/opt/scalar_replacement_pass.cpp
  source/opt/scalar_replacement_pass.h
  test/opt/scalar_replacement_test.cpp
Labels: bug, fuzzer-found-issue

#2774 Protect against out-of-bounds references when folding OpCompositeExtract
  source/opt/const_folding_rules.cpp
  test/opt/fold_test.cpp
Labels: bug, fuzzer-found-issue

#2775 Update OpMemoryBarriers rules for WebGPU
  source/val/validate_memory_semantics.cpp
  source/val/validate_scopes.cpp
  test/val/val_barriers_test.cpp
Labels: api:webgpu, component:validation

#2777 Update WebGPU validation rules of OpAtomic*s
  source/val/validate_memory_semantics.cpp
  source/val/validate_scopes.cpp
  test/val/val_atomics_test.cpp
Labels: api:webgpu, component:validation, enhancement
