Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2019-02, with the labels that each got.

#2341 Mention the reducer tool and location in the README.
  README.md
Labels: component:reducer

#2348 Add flatten-decorations flag to webgpu-mode flags
  source/opt/optimizer.cpp
  test/opt/optimizer_test.cpp
Labels: api:webgpu, component:optimization

#2361 Fixes #2358. Added to the reducer the ability to remove a function t…
  Android.mk
  BUILD.gn
  source/opt/CMakeLists.txt
  source/opt/eliminate_dead_functions_pass.cpp
  source/opt/eliminate_dead_functions_util.cpp
  source/opt/eliminate_dead_functions_util.h
  source/reduce/CMakeLists.txt
  source/reduce/remove_function_reduction_opportunity.cpp
  source/reduce/remove_function_reduction_opportunity.h
  source/reduce/remove_function_reduction_opportunity_finder.cpp
  source/reduce/remove_function_reduction_opportunity_finder.h
  test/reduce/CMakeLists.txt
  test/reduce/remove_function_test.cpp
  tools/reduce/reduce.cpp
Labels: component:reducer

#2365 Add better error message to ValidateInstructions
  test/val/val_fixtures.h
Labels: enhancement

#2368 Add strip-debug to webgpu-mode passes
  source/opt/optimizer.cpp
  test/opt/optimizer_test.cpp
Labels: api:webgpu, component:optimization

#2395 Refactor webgpu-mode pass ran tests to be parameterized
  test/opt/optimizer_test.cpp
Labels: api:webgpu, component:optimization, enhancement

#2402 Fixup unused variables
  source/opt/instrument_pass.cpp
Labels: dev:building
