Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2019-03, with the labels that each got.

#2386 Implement WebGPU specific CFG validation
  source/val/function.cpp
  source/val/function.h
  source/val/validate_cfg.cpp
  test/val/val_cfg_test.cpp
Labels: api:webgpu, component:validation

#2440 Add missing DepthGreater case to Fragment only check
  source/val/validate_mode_setting.cpp
  test/val/val_modes_test.cpp
Labels: bug, component:validation

#2443 Add validation for ExecutionMode in WebGPU
  source/val/validate_mode_setting.cpp
  test/val/val_modes_test.cpp
Labels: api:webgpu, component:validation

#2446 Add validation of storage classes for WebGPU
  source/val/validate_instruction.cpp
  test/val/val_storage_test.cpp
Labels: api:webgpu, component:validation

#2413 Add --strip-atomic-counter-memory
  Android.mk
  BUILD.gn
  include/spirv-tools/optimizer.hpp
  source/opcode.cpp
  source/opcode.h
  source/opt/CMakeLists.txt
  source/opt/optimizer.cpp
  source/opt/passes.h
  source/opt/strip_atomic_counter_memory_pass.cpp
  source/opt/strip_atomic_counter_memory_pass.h
  test/opt/CMakeLists.txt
  test/opt/optimizer_test.cpp
  test/opt/strip_atomic_counter_memory_test.cpp
  tools/opt/opt.cpp
Labels: api:webgpu, component:optimization

#2464 Convert sampled consumers to being Instructions instead of IDs
  source/val/validate_image.cpp
  source/val/validation_state.cpp
  source/val/validation_state.h
  test/val/val_image_test.cpp
Labels: bug, component:validation

#2398 reduce: remove unreferenced blocks pass
  source/reduce/CMakeLists.txt
  source/reduce/remove_block_reduction_opportunity.cpp
  source/reduce/remove_block_reduction_opportunity.h
  source/reduce/remove_block_reduction_opportunity_finder.cpp
  source/reduce/remove_block_reduction_opportunity_finder.h
  test/reduce/CMakeLists.txt
  test/reduce/remove_block_test.cpp
Labels: component:reducer

#2401 Add some val options to reduce
  source/reduce/reducer.cpp
  source/reduce/reducer.h
  test/reduce/reducer_test.cpp
  test/reduce/validation_during_reduction_test.cpp
  tools/reduce/reduce.cpp
Labels: component:reducer

#2467 Check OpSampledImage is only passed into valid instructions
  source/val/validate_image.cpp
  test/val/val_image_test.cpp
Labels: component:validation
