Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2019-04, with the labels that each got.

#2481 Add pass to generate needed initializers for WebGPU
  Android.mk
  BUILD.gn
  include/spirv-tools/optimizer.hpp
  source/opt/CMakeLists.txt
  source/opt/generate_webgpu_initializers_pass.cpp
  source/opt/generate_webgpu_initializers_pass.h
  source/opt/optimizer.cpp
  source/opt/passes.h
  test/opt/CMakeLists.txt
  test/opt/generate_webgpu_initializers_test.cpp
  test/opt/optimizer_test.cpp
  tools/opt/opt.cpp
Labels: api:webgpu, component:optimization, enhancement

#2493 Fix webgpu header file name in BUILD.gn
  BUILD.gn
Labels: bug

#2496 Add WebGPU->Vulkan and Vulkan->WebGPU flags in spirv-opt
  include/spirv-tools/optimizer.hpp
  source/opt/optimizer.cpp
  test/opt/optimizer_test.cpp
  tools/opt/opt.cpp
Labels: api:vulkan, api:webgpu, component:optimization

#2505 Accept OpBitCast in fix storage class.
  source/opt/fix_storage_class.cpp
  test/opt/fix_storage_class_test.cpp
Labels: fuzzer

#2509 Add pass to legalize OpVectorShuffle for WebGPU
  Android.mk
  BUILD.gn
  include/spirv-tools/optimizer.hpp
  source/opt/CMakeLists.txt
  source/opt/legalize_vector_shuffle_pass.cpp
  source/opt/legalize_vector_shuffle_pass.h
  source/opt/optimizer.cpp
  source/opt/passes.h
  test/opt/CMakeLists.txt
  test/opt/legalize_vector_shuffle_test.cpp
  test/opt/optimizer_test.cpp
Labels: api:webgpu, component:validation

#2519 Change validation of memory semantics for OpAtomics* in WebGPU
  source/val/validate_memory_semantics.cpp
  test/val/val_atomics_test.cpp
Labels: api:webgpu, component:validation, enhancement

#2523 Validate that SPIR-V binary is encoded as little endian for WebGPU
  source/val/validate.cpp
  test/val/val_webgpu_test.cpp
Labels: api:webgpu, component:validation, enhancement

#2530 Remove legacy utility functions
  source/val/validate.cpp
Labels: component:validation, dev:building

#2526 Remove Acquire and Release from allowed Mem Sem bits for WebGPU
  source/val/validate_memory_semantics.cpp
  test/val/val_barriers_test.cpp
Labels: api:webgpu, component:validation, enhancement

#2537 Add support for Private & Output to initializer decompose flag
  source/opt/decompose_initialized_variables_pass.cpp
  test/opt/decompose_initialized_variables_test.cpp
Labels: api:vulkan, api:webgpu, component:optimization
