Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2019-01, with the labels that each got.

#2258 Handle CompositeInsert with no indices in VDCE
  source/opt/vector_dce.cpp
  test/opt/vector_dce_test.cpp
Labels: fuzzer

#2261 Have replace load size handle extact with no index.
  source/opt/reduce_load_size.cpp
  test/opt/reduce_load_size_test.cpp
Labels: fuzzer

#2262 [kokoro] Fix usage of ERRORLEVEL in Windows script.
  kokoro/scripts/windows/build.bat
Labels: dev:ci

#2281 Ensure that entry point names are unique for WebGPU
  source/val/validate.cpp
  test/val/val_validation_state_test.cpp
Labels: api:webgpu, component:validation

#2283 Removing unused const version of id_decorations
  source/val/validation_state.h
Labels: component:validation

#2191 Enforce rules for OpTypeRuntimeArray on Vulkan
  source/val/validate_memory.cpp
  source/val/validate_type.cpp
  source/val/validation_state.h
  test/val/val_data_test.cpp
  test/val/val_memory_test.cpp
Labels: api:vulkan, component:validation

#2285 Ensure that required storage classes have initializer for WebGPU
  source/val/validate_memory.cpp
  test/val/val_memory_test.cpp
Labels: api:webgpu, component:validation

#2289 Add tests to validate allowed lengths of int and floats for WebGPU
  test/val/val_data_test.cpp
Labels: api:webgpu, component:validation

#2292 Fix up bit shifts by 32.
  source/opt/fold.cpp
  test/opt/fold_test.cpp
Labels: fuzzer

#2287 Add WebGPU specific RTA validation rules
  source/val/validate_memory.cpp
  source/val/validate_type.cpp
  test/val/val_data_test.cpp
  test/val/val_memory_test.cpp
Labels: api:webgpu, component:validation

#2288 Add in WebGPU specific memory scope validation
  source/val/validate_scopes.cpp
  test/val/val_atomics_test.cpp
Labels: api:webgpu, component:validation

#2293 Fix overflow when negating INT_MIN.
  source/opt/fold.cpp
  test/opt/fold_test.cpp
Labels: fuzzer

#2304 Handle access chain with no index in SROA.
  source/opt/scalar_replacement_pass.cpp
  test/opt/scalar_replacement_test.cpp
Labels: fuzzer

#2308 Handle instructions not in blocks in code sinking.
  source/opt/code_sink.cpp
  test/opt/code_sink_test.cpp
Labels: fuzzer

#2307 Check forward reference in OpTypeArray.
  source/val/validate_datarules.cpp
  test/val/val_data_test.cpp
Labels: fuzzer

#2309 Add WebGPU specific validation for Position BuiltIn decoration
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: api:webgpu, component:validation

#2343 Move CodeGenerator to be accessible by other validation tests
  test/val/CMakeLists.txt
  test/val/val_builtins_test.cpp
  test/val/val_code_generator.cpp
  test/val/val_code_generator.h
Labels: component:validation

#2328 Add WebGPU specific validation for VertexIndex BuiltIn decoration
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: api:webgpu, component:validation

#2330 Add WebGPU specific validation for FrontFacing BuiltIn decoration
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: api:webgpu, component:validation

#2331 Add WebGPU specific validation for FragCoord BuiltIn decoration
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: api:webgpu, component:validation

#2335 Add WebGPU validation for LocalInvocationIndex BuiltIn decoration
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: api:webgpu, component:validation

#2337 Add whitelist of allowed BuiltIn decorations for WebGPU
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: api:webgpu, component:validation

#2333 Add WebGPU specific validation for multiple BuiltIn decorations
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: api:webgpu, component:validation

#2334 Add WebGPU specific validation for WorkgroupSize BuiltIn decoration
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: api:webgpu, component:validation

#2339 Fixes #2338. Added functionality to remove OpPhi instructions (replacing their uses) when merging blocks
  source/opt/block_merge_util.cpp
  test/opt/block_merge_test.cpp
Labels: component:optimization, kokoro:run
