Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2019-05, with the labels that each got.

#2542 Remove stale comment
  source/val/validate_mode_setting.cpp
Labels: component:validation

#2536 Add validation specific to OpExecutionModeId
  source/val/validate_mode_setting.cpp
  test/val/val_modes_test.cpp
Labels: component:validation

#2563 Add pass to fix some invalid unreachable blocks for WebGPU
  Android.mk
  BUILD.gn
  include/spirv-tools/optimizer.hpp
  source/opt/CMakeLists.txt
  source/opt/function.cpp
  source/opt/function.h
  source/opt/optimizer.cpp
  source/opt/passes.h
  source/opt/split_invalid_unreachable_pass.cpp
  source/opt/split_invalid_unreachable_pass.h
  test/opt/CMakeLists.txt
  test/opt/optimizer_test.cpp
  test/opt/split_invalid_unreachable_test.cpp
Labels: api:webgpu, component:optimization

#2582 Handle id overflow in sroa better.
  source/opt/constants.cpp
  source/opt/ir_context.h
  source/opt/scalar_replacement_pass.cpp
  source/opt/scalar_replacement_pass.h
  test/opt/scalar_replacement_test.cpp
Labels: fuzzer

#2615 Add in individual flags for Vulkan <-> WebGPU passes
  source/opt/optimizer.cpp
  tools/opt/opt.cpp
Labels: component:optimization

#2576 Remove MarkV and Stats code.
  .appveyor.yml
  Android.mk
  CMakeLists.txt
  README.md
  kokoro/android/build.sh
  kokoro/scripts/windows/build.bat
  source/CMakeLists.txt
  source/comp/CMakeLists.txt
  source/comp/bit_stream.cpp
  source/comp/bit_stream.h
  source/comp/huffman_codec.h
  source/comp/markv.cpp
  source/comp/markv.h
  source/comp/markv_codec.cpp
  source/comp/markv_codec.h
  source/comp/markv_decoder.cpp
  source/comp/markv_decoder.h
  source/comp/markv_encoder.cpp
  source/comp/markv_encoder.h
  source/comp/markv_logger.h
  source/comp/markv_model.h
  source/comp/move_to_front.cpp
  source/comp/move_to_front.h
  source/id_descriptor.cpp
  source/id_descriptor.h
  test/CMakeLists.txt
  test/bit_stream.cpp
  test/comp/CMakeLists.txt
  test/comp/markv_codec_test.cpp
  test/huffman_codec.cpp
  test/move_to_front_test.cpp
  test/stats/CMakeLists.txt
  test/stats/stats_aggregate_test.cpp
  test/stats/stats_analyzer_test.cpp
  tools/CMakeLists.txt
  tools/comp/markv.cpp
  tools/comp/markv_model_factory.cpp
  tools/comp/markv_model_factory.h
  tools/comp/markv_model_shader.cpp
  tools/comp/markv_model_shader.h
  tools/comp/markv_model_shader_default_autogen.inc
  tools/stats/spirv_stats.cpp
  tools/stats/spirv_stats.h
  tools/stats/stats.cpp
  tools/stats/stats_analyzer.cpp
  tools/stats/stats_analyzer.h
Labels: component:compression, dev:refactoring

#2625 Add fuzzer for WebGPU->Vulkan spirv-opt passes
  test/fuzzers/BUILD.gn
  test/fuzzers/spvtools_opt_webgputovulkan_fuzzer.cpp
Labels: component:optimization

#2626 Add fuzzer for Vulkan->WebGPU spirv-opt passes
  test/fuzzers/BUILD.gn
  test/fuzzers/spvtools_opt_vulkantowebgpu_fuzzer.cpp
Labels: component:optimization

#2628 Add WebGPU specific fuzzer for validation
  test/fuzzers/BUILD.gn
  test/fuzzers/spvtools_val_webgpu_fuzzer.cpp
Labels: component:validation

#2639 Add compact ids to WebGPU <-> Vulkan transformations
  source/opt/optimizer.cpp
  test/opt/optimizer_test.cpp
Labels: component:optimization

#2644 Close opened file handles.
  tools/io.h
Labels: bug

#2646 Remove asserts from GetUnderlyingType
  source/val/validate_builtins.cpp
  test/val/val_builtins_test.cpp
Labels: component:validation
