Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2020-02, with the labels that each got.

#3170 Fix typos in opt's help. Update environment version.
  tools/opt/opt.cpp
Labels: component:optimization

#3133 Add validation rules for OpenCL.DebugInfo.100 extension
  source/val/validate_extensions.cpp
  source/val/validate_id.cpp
  test/val/val_ext_inst_test.cpp
Labels: component:validation

#3204 Adding WebGPU specific Workgroup scope rule
  source/val/validate_scopes.cpp
  test/val/val_barriers_test.cpp
Labels: api:webgpu, component:validation
