Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2020-06, with the labels that each got.

#3389 Add tests for merge-return debug info preservation
  test/opt/pass_merge_return_test.cpp
Labels: component:optimization

#3420 Debug info preservation in ccp pass
  test/opt/ccp_test.cpp
Labels: component:optimization

#3433 Update access control lists.
  source/operand.cpp
  source/opt/aggressive_dead_code_elim_pass.cpp
  source/opt/aggressive_dead_code_elim_pass.h
  source/opt/local_access_chain_convert_pass.cpp
  source/opt/local_access_chain_convert_pass.h
  source/opt/local_single_block_elim_pass.cpp
  source/opt/local_single_block_elim_pass.h
  source/opt/local_single_store_elim_pass.cpp
  source/opt/local_single_store_elim_pass.h
  test/opt/aggressive_dead_code_elim_test.cpp
  test/val/val_builtins_test.cpp
  test/val/val_decoration_test.cpp
  test/val/val_modes_test.cpp
  test/val/val_webgpu_test.cpp
  utils/check_symbol_exports.py
Labels: dev:refactoring

#3425 Debug info preservation in dead branch elimination
  test/opt/dead_branch_elim_test.cpp
  test/opt/ir_context_test.cpp
Labels: component:optimization

#3356 [spirv-opt] debug info preservation in ssa-rewrite
  source/opt/debug_info_manager.cpp
  source/opt/debug_info_manager.h
  source/opt/ir_context.cpp
  source/opt/ir_context.h
  source/opt/mem_pass.cpp
  source/opt/pass.h
  source/opt/ssa_rewrite_pass.cpp
  source/opt/ssa_rewrite_pass.h
  test/opt/local_ssa_elim_test.cpp
Labels: component:optimization

#3442 Add support for different default branches in roll-deps
  utils/roll_deps.sh
Labels: enhancement

#3459 Clear debug information for kill and replacement
  source/opt/debug_info_manager.cpp
  source/opt/debug_info_manager.h
  source/opt/ir_context.cpp
  test/opt/ir_context_test.cpp
  test/opt/local_ssa_elim_test.cpp
Labels: component:optimization

#3470 Fix ADCE pass bug for mulitple entries
  source/opt/aggressive_dead_code_elim_pass.cpp
  source/opt/aggressive_dead_code_elim_pass.h
  test/opt/aggressive_dead_code_elim_test.cpp
Labels: component:optimization

#3391 spirv-fuzz: Add FuzzerPassAddCopyMemoryInstructions
  source/fuzz/CMakeLists.txt
  source/fuzz/fuzzer.cpp
  source/fuzz/fuzzer_context.cpp
  source/fuzz/fuzzer_context.h
  source/fuzz/fuzzer_pass_add_copy_memory.cpp
  source/fuzz/fuzzer_pass_add_copy_memory.h
  source/fuzz/protobufs/spvtoolsfuzz.proto
  source/fuzz/transformation.cpp
  source/fuzz/transformation_add_copy_memory.cpp
  source/fuzz/transformation_add_copy_memory.h
  test/fuzz/CMakeLists.txt
  test/fuzz/transformation_add_copy_memory_test.cpp
Labels: kokoro:run
