Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2020-08, with the labels that each got.

#3651 spirv-fuzz: Handle capabilities during module donation
  source/fuzz/fuzzer_pass_donate_modules.cpp
  test/fuzz/fuzzer_pass_donate_modules_test.cpp
Labels: kokoro:run

#3549 OpenCL.DebugInfo.100 DebugTypeArray with variable size
  source/val/validate_extensions.cpp
  test/val/val_ext_inst_test.cpp
Labels: component:validation

#3684 Validate OpenCL.DebugInfo.100 instructions for legalization passes
  source/val/validate_extensions.cpp
  test/val/val_ext_inst_test.cpp
Labels: component:validation

#3652 Preserve debug info in dead-insert-elim pass
  source/opt/dead_insert_elim_pass.cpp
  test/opt/dead_insert_elim_test.cpp
Labels: component:optimization

#3693 Improve non-semantic instruction handling in the optimizer
  source/opt/aggressive_dead_code_elim_pass.cpp
  source/opt/aggressive_dead_code_elim_pass.h
  source/opt/eliminate_dead_functions_util.cpp
  source/opt/function.cpp
  source/opt/function.h
  source/opt/instruction.cpp
  source/opt/instruction.h
  source/opt/ir_context.cpp
  source/opt/ir_context.h
  source/opt/ir_loader.cpp
  source/opt/module.cpp
  test/opt/eliminate_dead_functions_test.cpp
  test/opt/function_test.cpp
  test/opt/module_test.cpp
  test/opt/strip_reflect_info_test.cpp
Labels: component:optimization

#3702 Allow DebugTypeTemplate for Type operand
  source/val/validate_extensions.cpp
  test/val/val_ext_inst_test.cpp
Labels: component:validation

#3703 Let ADCE pass check DebugScope
  source/opt/aggressive_dead_code_elim_pass.cpp
  test/opt/aggressive_dead_code_elim_test.cpp
Labels: component:optimization

#3724 Handle DebugScope in compact-ids pass
  source/opt/compact_ids_pass.cpp
  source/opt/instruction.h
  test/opt/compact_ids_test.cpp
Labels: component:optimization

#3718 Correctly replace debug lexical scope of instruction
  source/opt/debug_info_manager.cpp
  source/opt/debug_info_manager.h
  source/opt/instruction.cpp
  source/opt/instruction.h
  source/opt/ir_context.cpp
  source/opt/ir_context.h
  source/opt/simplification_pass.cpp
  test/opt/ir_context_test.cpp
Labels: component:optimization
