Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2020-04, with the labels that each got.

#3269 Set wrapped kill basic block's parent
  source/opt/wrap_opkill.cpp
  test/opt/wrap_opkill_test.cpp
Labels: bug

#3271 Update dominates to check for null nodes
  source/opt/dominator_tree.cpp
  test/opt/loop_optimizations/loop_descriptions.cpp
Labels: bug, component:optimization

#3251 Preserve debug info in eliminate-dead-functions
  source/opt/feature_manager.cpp
  source/opt/feature_manager.h
  source/opt/function.cpp
  source/opt/instruction.cpp
  source/opt/instruction.h
  source/opt/ir_context.cpp
  source/opt/ir_context.h
  source/opt/type_manager.h
  test/opt/eliminate_dead_functions_test.cpp
  test/opt/ir_context_test.cpp
Labels: component:optimization

#3305 Add debug information analysis
  Android.mk
  BUILD.gn
  source/opt/CMakeLists.txt
  source/opt/debug_info_manager.cpp
  source/opt/debug_info_manager.h
  source/opt/ir_context.cpp
  source/opt/ir_context.h
  test/opt/CMakeLists.txt
  test/opt/debug_info_manager_test.cpp
  test/opt/eliminate_dead_functions_test.cpp
Labels: component:optimization

#3323 Set DebugScope for termination instructions
  source/opt/ir_loader.cpp
  test/opt/ir_loader_test.cpp
Labels: component:optimization
