Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2020-09, with the labels that each got.

#3814 Fix missed modification flagging
  source/opt/graphics_robust_access_pass.cpp
  test/opt/graphics_robust_access_test.cpp
Labels: api:webgpu, component:optimization

#3834 Validate SPIRV Version number when parsing binary header
  source/binary.cpp
  test/binary_header_get_test.cpp
  test/link/binary_version_test.cpp
Labels: component:validation

#3847 [spirv-dis] Add some context comments to disassembly.
  include/spirv-tools/libspirv.h
  source/disassemble.cpp
  tools/dis/dis.cpp
Labels: component:as/dis
