Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2020-05, with the labels that each got.

#3331 Preserve debug info for wrap-opkill
  source/opt/instruction.h
  source/opt/wrap_opkill.cpp
  test/opt/wrap_opkill_test.cpp
Labels: component:optimization, kokoro:run

#3328 [spirv-opt] refactor inlining pass
  source/opt/inline_pass.cpp
  source/opt/inline_pass.h
  test/opt/inline_opaque_test.cpp
  test/opt/inline_test.cpp
Labels: component:optimization

#3362 Handle OpConstantNull in ssa-rewrite
  source/opt/mem_pass.cpp
  test/opt/local_ssa_elim_test.cpp
Labels: component:optimization

#3349 Preserve debug info in inline pass
  source/opt/debug_info_manager.cpp
  source/opt/debug_info_manager.h
  source/opt/function.cpp
  source/opt/function.h
  source/opt/inline_pass.cpp
  source/opt/inline_pass.h
  source/opt/instruction.h
  test/opt/inline_test.cpp
Labels: component:optimization

#3374 spirv-val: allow DebugInfoNone for DebugTypeComposite.Size
  source/val/validate_extensions.cpp
  test/val/val_ext_inst_test.cpp
Labels: component:validation

#3380 Rolling 4 dependencies
  DEPS
Labels: dependencies
