Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2020-10, with the labels that each got.

#3861 Debug info preservation in if-conversion pass
  source/opt/if_conversion.cpp
  test/opt/if_conversion_test.cpp
Labels: component:optimization

#3839 Debug info preservation in redundancy-elimination pass
  source/opt/value_number_table.cpp
  test/opt/redundancy_elimination_test.cpp
  test/opt/value_table_test.cpp
Labels: component:optimization

#3835 Debug info preservation in convert-local-access-chains pass
  source/opt/local_access_chain_convert_pass.cpp
  test/opt/local_access_chain_convert_test.cpp
Labels: component:optimization

#3887 Update val to handle reversed instruction sections.
  source/val/validate_layout.cpp
  source/val/validation_state.cpp
  source/val/validation_state.h
  test/val/val_layout_test.cpp
  test/val/val_state_test.cpp
Labels: component:validation

#3923 Add DebugValue for function param regardless of scope
  source/opt/debug_info_manager.cpp
  source/opt/debug_info_manager.h
  test/opt/local_single_store_elim_test.cpp
Labels: component:optimization

#3988 spirv-fuzz: Don't replace irrelevant indices in OpAccessChain
  source/fuzz/fuzzer_pass_apply_id_synonyms.cpp
  source/fuzz/fuzzer_pass_replace_irrelevant_ids.cpp
  source/fuzz/fuzzer_util.cpp
  source/fuzz/fuzzer_util.h
  source/fuzz/transformation_replace_id_with_synonym.cpp
  source/fuzz/transformation_replace_irrelevant_id.cpp
  test/fuzz/transformation_replace_irrelevant_id_test.cpp
Labels: kokoro:run

#3973 Correct location of DebugValue for function param
  source/opt/debug_info_manager.cpp
  source/opt/debug_info_manager.h
  source/opt/instruction.cpp
  source/opt/local_single_store_elim_pass.cpp
  source/opt/ssa_rewrite_pass.cpp
  source/opt/ssa_rewrite_pass.h
  test/opt/ir_context_test.cpp
  test/opt/local_single_store_elim_test.cpp
  test/opt/local_ssa_elim_test.cpp
Labels: component:optimization

#4004 Temporarily add EmptyPass to prevent glslang from failing
  BUILD.gn
  include/spirv-tools/optimizer.hpp
  source/opt/CMakeLists.txt
  source/opt/empty_pass.h
  source/opt/optimizer.cpp
  source/opt/passes.h
Labels: component:optimization
