Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2020-12, with the labels that each got.

#4050 Take new (raytracing) termination instructions into account.
  source/opcode.cpp
  source/opcode.h
  source/opt/basic_block.cpp
  source/opt/inline_pass.cpp
  source/opt/ir_loader.cpp
  source/opt/module.cpp
  source/opt/reflect.h
  test/opt/inline_test.cpp
Labels: bug

#4044 Allow forward pointer to be used in types generally
  source/operand.cpp
  source/val/validate_id.cpp
  test/val/val_data_test.cpp
Labels: component:validation

#4067 Force using Python 3 git-sync-deps
  utils/git-sync-deps
Labels: component:general-utility
