Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2021-07, with the labels that each got.

#4379 spirv-opt: support SPV_EXT_shader_image_int64
  source/opt/aggressive_dead_code_elim_pass.cpp
  source/opt/local_access_chain_convert_pass.cpp
  source/opt/local_single_block_elim_pass.cpp
  source/opt/local_single_store_elim_pass.cpp
Labels: component:optimization

#4382 Fix build errors when UBSan's vptr check is enabled
  CMakeLists.txt
Labels: kokoro:run

#4348 spirv-fuzz: Support atomic operations opcode
  source/fuzz/transformation_replace_id_with_synonym.cpp
  test/fuzz/transformation_replace_id_with_synonym_test.cpp
Labels: kokoro:run

#4409 spirv-fuzz: Quit fuzzer pass when no types are available
  source/fuzz/fuzzer_pass_add_global_variables.cpp
Labels: component:fuzzer

#4415 spirv-fuzz: Add minimal SPIR-V example to test shaders
  test/fuzz/fuzzer_replayer_test.cpp
Labels: component:fuzzer

#4418 Fix validator crash
  source/val/validate_extensions.cpp
  test/val/val_ext_inst_test.cpp
Labels: component:validation
