Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2021-08, with the labels that each got.

#4449 Fix array layout validation slowdown
  source/val/validate_decorations.cpp
Labels: component:validation

#4446 Add new target for spirv-lint
  BUILD.bazel
  build_defs.bzl
  include/spirv-tools/linter.hpp
  source/CMakeLists.txt
  source/lint/CMakeLists.txt
  source/lint/linter.cpp
  test/CMakeLists.txt
  test/lint/CMakeLists.txt
  test/lint/placeholder_test.cpp
  tools/CMakeLists.txt
  tools/lint/lint.cpp
Labels: component:linter

#4459 Remove PCH from source/lint/CMakeLists.txt
  source/lint/CMakeLists.txt
Labels: component:linter

#4467 Limit location validation
  source/val/validate_interfaces.cpp
Labels: component:validation

#4473 Disallow loading a runtime-sized array
  source/val/validate_memory.cpp
  source/val/validation_state.cpp
  source/val/validation_state.h
  test/opt/eliminate_dead_member_test.cpp
  test/val/val_composites_test.cpp
  test/val/val_memory_test.cpp
Labels: component:validation

#4340 Add spirv-opt convert-to-sampled-image pass
  Android.mk
  BUILD.gn
  include/spirv-tools/optimizer.hpp
  source/opt/CMakeLists.txt
  source/opt/convert_to_sampled_image_pass.cpp
  source/opt/convert_to_sampled_image_pass.h
  source/opt/optimizer.cpp
  source/opt/passes.h
  test/opt/CMakeLists.txt
  test/opt/convert_to_sampled_image_test.cpp
  tools/opt/opt.cpp
Labels: component:optimization

#4474 Don't double count variables for location validation
  source/val/validate_interfaces.cpp
  test/val/val_interfaces_test.cpp
Labels: component:validation

#4478 spirv-lint: add basic CLI argument handling
  BUILD.bazel
  tools/lint/lint.cpp
Labels: component:linter

#4465 Add divergence analysis to linter
  BUILD.bazel
  source/lint/CMakeLists.txt
  source/lint/divergence_analysis.cpp
  source/lint/divergence_analysis.h
  test/lint/CMakeLists.txt
  test/lint/divergence_analysis_test.cpp
  test/lint/placeholder_test.cpp
Labels: component:linter
