Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2021-09, with the labels that each got.

#4499 Set threshold for reduce-load-size pass
  include/spirv-tools/optimizer.hpp
  source/opt/optimizer.cpp
  source/opt/reduce_load_size.cpp
  source/opt/reduce_load_size.h
  test/opt/reduce_load_size_test.cpp
  tools/opt/opt.cpp
Labels: component:optimization

#4507 Add some missing switch validation
  source/val/validate_cfg.cpp
  test/val/val_cfg_test.cpp
Labels: component:validation

#4519 Fix infinite loop in GetBlockDepth
  source/val/function.cpp
  test/val/val_cfg_test.cpp
Labels: component:validation

#4503 Change validator boolean tests to avoid asserts
  source/val/validation_state.cpp
  test/val/val_ext_inst_test.cpp
Labels: component:validation

#4523 Fix infinite loop in validation
  source/val/construct.cpp
  test/val/val_cfg_test.cpp
Labels: component:validation

#4414 spirv-fuzz: Account for differing signedness in WrapVectorSynonym
  source/fuzz/fuzzer_pass_apply_id_synonyms.cpp
  source/fuzz/fuzzer_pass_wrap_vector_synonym.cpp
  source/fuzz/fuzzer_util.cpp
  source/fuzz/fuzzer_util.h
  source/fuzz/transformation_replace_id_with_synonym.cpp
  source/fuzz/transformation_replace_id_with_synonym.h
  source/fuzz/transformation_wrap_vector_synonym.cpp
  source/fuzz/transformation_wrap_vector_synonym.h
  test/fuzz/fuzzerutil_test.cpp
  test/fuzz/transformation_replace_id_with_synonym_test.cpp
  test/fuzz/transformation_wrap_vector_synonym_test.cpp
Labels: component:fuzzer

#4531 Fix checks for offset in nested structs
  source/val/validate_decorations.cpp
  test/val/val_decoration_test.cpp
Labels: component:validation

#4555 Do not assume there are execution modes
  source/val/validate_derivatives.cpp
  test/val/val_derivatives_test.cpp
Labels: component:validation
