Repository KhronosGroup/SPIRV-Tools, pull requests merged in 2022-12, with the labels that each got.

#5013 Fix use of invalid analysis
  source/opt/block_merge_util.cpp
  test/opt/block_merge_test.cpp
Labels: bug, component:optimization

#5015 Fix layout validation
  source/val/validate_decorations.cpp
  test/val/val_decoration_test.cpp
Labels: component:validation

#5025 Fix undef behaviour in hex float parsing
  source/util/hex_float.h
  test/hex_float_test.cpp
Labels: fuzzer-found-issue
